In [20]:
# Versão da Linguagem Python
from platform import python_version
print('Versão de Python Neste Jupyter Notebook:', python_version())

# usaremos o filtro 'warning' para deixar mais limpo.
import warnings
warnings.filterwarnings('ignore')

Versão de Python Neste Jupyter Notebook: 3.10.5


#### Criando dados de amostra para análise

In [21]:
# importação de dados
from sklearn import datasets
from sklearn.datasets import load_boston

In [23]:
# metodos disponiveis para os conjuntos de daados
datasets.make_*?

datasets.make_biclusters
datasets.make_blobs
datasets.make_checkerboard
datasets.make_circles
datasets.make_classification
datasets.make_friedman1
datasets.make_friedman2
datasets.make_friedman3
datasets.make_gaussian_quantiles
datasets.make_hastie_10_2
datasets.make_low_rank_matrix
datasets.make_moons
datasets.make_multilabel_classification
datasets.make_regression
datasets.make_s_curve
datasets.make_sparse_coded_signal
datasets.make_sparse_spd_matrix
datasets.make_sparse_uncorrelated
datasets.make_spd_matrix
datasets.make_swiss_roll

In [24]:
import numpy as np

In [25]:
# dados para uso de regressão linear
reg_data = datasets.make_regression()

In [26]:
# criandos dados para regressão
complex_reg_data = datasets.make_regression(n_samples = 1000,
                                            n_features = 10,
                                            noise = 5,
                                            random_state = 2)
complex_reg_data[0].shape

(1000, 10)

In [27]:
# visualizandos os dados
print(complex_reg_data)

(array([[ 0.66291989,  1.64691879,  0.16543216, ..., -0.64363161,
        -0.83388616,  1.84734512],
       [-0.78747362,  0.94585768, -0.69783996, ..., -1.1937438 ,
         0.00699965, -1.35721846],
       [-1.45902935,  1.59065989,  0.25663715, ...,  0.40262807,
        -1.26397499, -1.4332651 ],
       ...,
       [-0.7271977 , -1.25571846,  0.03966606, ...,  0.64582622,
        -0.21094545,  0.55951044],
       [-0.51978105,  1.75985301,  0.65304541, ..., -0.36450887,
         0.09394812, -0.15502609],
       [-0.63405313, -0.15440996, -0.98649636, ..., -1.7492888 ,
         2.3263909 , -0.31481184]]), array([ 1.54983483e+02,  1.90085063e+01, -8.89327622e+00,  6.18794466e+01,
        8.84436386e+01, -1.50165724e+02, -2.57513148e+02, -1.13039646e+02,
       -2.01324395e+02,  1.96820544e+02, -1.46448448e+02, -1.43847007e+01,
        2.85571428e+02,  4.22508154e+01,  9.25470576e+01,  1.41044595e+02,
        6.34058944e+01, -8.91024294e+01,  7.94524322e+01, -1.27264757e+02,
       -3.

In [28]:
# criando dados para classificação
classification_set = datasets.make_classification(weights = [0.1])
np.bincount(classification_set[1])

array([11, 89], dtype=int64)

In [29]:
# visualizandos os dados
print(classification_set)

(array([[ 0.10578496,  0.13241204,  1.81091381, ..., -1.74950359,
        -1.29276749, -0.53778348],
       [-2.1703115 ,  1.93163523, -2.21642102, ..., -0.31074951,
        -0.2572568 ,  1.8970078 ],
       [-0.5374102 , -1.47364427,  0.4700888 , ..., -0.85167177,
        -0.10697412,  0.32481563],
       ...,
       [ 0.92973475, -1.14652637, -0.91292554, ...,  0.64935957,
         0.32827829,  0.51744485],
       [ 0.1286915 , -1.44259563, -0.89989996, ...,  0.13408804,
        -0.04047003,  0.38584762],
       [ 0.27451282, -0.55352999,  1.41762277, ...,  1.26095535,
        -1.40919373,  0.1499499 ]]), array([1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))


In [30]:
# criando dados de cluster
blobs = datasets.make_blobs()

In [31]:
# visualizandos os dados
print(blobs)

(array([[-1.64787310e-01, -3.53465085e+00],
       [ 2.30070690e-01, -4.21410128e+00],
       [-1.66178241e+00, -4.74913299e+00],
       [-7.08105310e-02, -1.01425379e+00],
       [ 4.32713803e-01, -1.71878559e+00],
       [-1.41463522e+00, -4.56225384e+00],
       [-3.13862041e+00, -2.49474809e+00],
       [ 2.46124961e+00,  6.15950501e+00],
       [ 7.35084795e-01, -3.99471377e+00],
       [ 1.04487838e+00,  4.38522257e-01],
       [ 2.24346571e+00,  5.93820926e+00],
       [ 4.48803160e+00,  7.46045289e+00],
       [-4.74992607e-01, -1.65426324e+00],
       [-6.28107550e-02, -3.97967036e+00],
       [-1.85439210e+00, -3.78572239e+00],
       [ 3.18015108e+00,  6.34600825e+00],
       [-8.28593740e-01, -2.20570443e+00],
       [ 2.93539014e+00,  4.84820290e+00],
       [-4.59752552e-01, -2.98689489e+00],
       [-1.50302772e-01, -1.72026085e+00],
       [-1.01526048e+00, -4.74270926e+00],
       [ 3.43932137e+00,  6.07969335e+00],
       [ 3.54139038e+00,  6.13685176e+00],
       [-7

In [33]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

Author: Caique Miranda

Github username: caiquemiranda

sklearn: 1.1.1
numpy  : 1.23.0



### End.