In [3]:
# Versão da Linguagem Python
from platform import python_version
print('Versão de Python Neste Jupyter Notebook:', python_version())

# usaremos o filtro 'warning' para deixar mais limpo.
import warnings
warnings.filterwarnings('ignore')

Versão de Python Neste Jupyter Notebook: 3.10.5


#### Escalando dados para o padrão normal

In [4]:
from sklearn.datasets import load_boston

In [5]:
# carregando dados do conjunto de casas de boston
boston = load_boston()
X, y = boston.data, boston.target

In [6]:
from sklearn import preprocessing
import numpy as np

Essa tecninca padroniza as variaveis removendo a média e escala a variância a uma unidade.deixando que para cada caracteristica, a média seria 0, e o desvio Padrão seria 1.Assim, as caracteristicas são padronizadas, tornando-as mais manejáveis para nossos modelos

In [7]:
X[:, :3].mean(axis = 0)
X[:, :3].std(axis = 0)

array([ 8.59304135, 23.29939569,  6.85357058])

In [8]:
X_2 = preprocessing.scale(X[:, :3])

X_2.mean(axis = 0)

X_2.std(axis = 0)

array([1., 1., 1.])

In [9]:
# StandardScaler
my_scaler = preprocessing.StandardScaler()
my_scaler.fit(X[:, :3])
my_scaler.transform(X[:, :3]).mean(axis = 0)

array([-8.78743718e-17, -6.34319123e-16, -2.68291099e-15])

In [10]:
# MinMaxScaler
my_minmax_scaler = preprocessing.MinMaxScaler()
my_minmax_scaler.fit(X[:, :3])
my_minmax_scaler.transform(X[:, :3]).max(axis = 0)

array([1., 1., 1.])

In [11]:
my_odd_scaler = preprocessing.MinMaxScaler(feature_range=(-3.14, 3.14))

In [12]:
normalized_X = preprocessing.normalize(X[:, :3])

In [13]:
my_useless_scaler = preprocessing.StandardScaler(with_mean = False,
                                                 with_std = False)

In [14]:
transformed_sd = my_useless_scaler.fit_transform(X[:, :3]).std(axis = 0)

In [15]:
original_sd = X[:, :3].std(axis=0)
np.array_equal(transformed_sd, original_sd)

True

In [16]:
import scipy

In [19]:
matrix = scipy.sparse.eye(1000)
preprocessing.scale(matrix, 
                    with_mean = False)

<1000x1000 sparse matrix of type '<class 'numpy.float64'>'
	with 1000 stored elements in Compressed Sparse Column format>

In [21]:
print(matrix)

  (0, 0)	1.0
  (1, 1)	1.0
  (2, 2)	1.0
  (3, 3)	1.0
  (4, 4)	1.0
  (5, 5)	1.0
  (6, 6)	1.0
  (7, 7)	1.0
  (8, 8)	1.0
  (9, 9)	1.0
  (10, 10)	1.0
  (11, 11)	1.0
  (12, 12)	1.0
  (13, 13)	1.0
  (14, 14)	1.0
  (15, 15)	1.0
  (16, 16)	1.0
  (17, 17)	1.0
  (18, 18)	1.0
  (19, 19)	1.0
  (20, 20)	1.0
  (21, 21)	1.0
  (22, 22)	1.0
  (23, 23)	1.0
  (24, 24)	1.0
  :	:
  (975, 975)	1.0
  (976, 976)	1.0
  (977, 977)	1.0
  (978, 978)	1.0
  (979, 979)	1.0
  (980, 980)	1.0
  (981, 981)	1.0
  (982, 982)	1.0
  (983, 983)	1.0
  (984, 984)	1.0
  (985, 985)	1.0
  (986, 986)	1.0
  (987, 987)	1.0
  (988, 988)	1.0
  (989, 989)	1.0
  (990, 990)	1.0
  (991, 991)	1.0
  (992, 992)	1.0
  (993, 993)	1.0
  (994, 994)	1.0
  (995, 995)	1.0
  (996, 996)	1.0
  (997, 997)	1.0
  (998, 998)	1.0
  (999, 999)	1.0


In [ ]:
%reload_ext watermark
%watermark -a "Caique Miranda" -gu "caiquemiranda" -iv

### End.